### PR TITLE
Add ability to print from a zip of png images.

### PR DESCRIPTION
**Pull request by jmkao**
Even with built-in STL slicing, there will probably be some time before you can do model positioning on the plate in the web UI. In the meantime, I've created a file processor that will print images from a zip file, but still use the CWH templated logic.

I have set the acceptsFile() for this processor to take files that end in .imgzip, and have a routine that will quickly count the number of non-black pixels in a image to give an area in pixels, and then used the same logic you had in the STLFileProcessor to convert that into mm^2 area.

I extended CreationWorkshopSceneFileProcessor because 99.99% of all of the unpack/cleanup logic for handing the file was identical. There was one change that I made to the CreationWorkshopSceneFileProcessor, which is that the private unpackDir method calls findGcodeFile(jobFile), even though processFile calls that function again. In order to save the redundant logic of having to duplicate the code for prepareEnvironment and unpackDir, I commented out that line. I'm not sure if there was a particular reason that findGcodeFile is executed twice in the processing pipeline for a CWS file, so that section especially would be worth a review.

I've tested this code in a print and it seems to be free of off-by-one errors, and I used some of the same Future<> techniques you used in the STLFileProcessor to do applyMask and the pixel counting during the exposure/lift sequence.

Since my Java is much stronger than my HTML/JavaScript, I have not yet looked into how to hook this up with the UI that connects processors to specific file type icons, so for now, the file type icon is a ?.

The workflow I imagine for this format is the use of a slicer like Materialise Magics or Asiga Stomp (both of which slice much faster than CW and much more professional, the latter is free), and then a tool like slc2png to convert the multilayered svg or SLC file into a set of PNGs. Secondarily, this could be used by anyone who uses a workflow ending with projectlayer to then use CWH instead, with whatever workflow they may be using to generate PNG slices.

### CODE REVIEW

**Comment by jmkao** [comment]
Oh, one more thing, there were a few minor issues with the eclipse configuration files that were checked into github. The main problem was a lingering reference to a jsch jar, which doesn't seem to be in the libs directory anymore. I had to take that out of the project configuration to restore incremental build capability.

A secondary issue is that I had an implementation that initially used a lambda for the Future, and needed the target upped to JDK 1.8. I ended up factoring the lambda out, but left the target set to 1.8 since that seems to be what the RPi has a default anyway. If you have a problem with that, I can revert those changes.

**Comment by WesGilster** [comment]
So cool. Awesome to see people building new file processors. The abstract 3d printing is an area where the real power of CWH shows through. Keep in mind that these print file processors are designed to share file types if you feel like your print file processor deserves the same ownership over an extension. In that situation, your acceptsFile() method needs to perform a stronger introspection of the file contents than just "does the file have a zip extension". That would also mean that you'd need to modify other print file processors(that share your extension) to perform a separate introspection to detect their own magics. If your content is identical to CWH or ZIP, there isn't much you can do besides change the extension exactly as you've done.

Eventually when the userbase becomes significant enough we'll need to be more disciplined about writing tests. I haven't been good about it either and I'm not really interested in slowing development down right now.

I'll merge this in with my branch and push out when I push out the remote install process. Most likely tomorrow or the next.

If you want, you can pick out an icon from:
https://fortawesome.github.io/Font-Awesome/icons/

I need to merge the two functions that perform the icon selection in two different controllers:
getPrintableIconClass() printables.js
getPrintJobIconClass() printjob.js

**Comment by jmkao** [comment]
Yes, the way that the rest of the framework calls the file processors for "macro level" lifecycle and then  processFile calls the inherited methods from the base class for "micro level" slice operations makes it very easy to implement. I'd estimate about 2-3 hours to browse the code and setup the build environment, and another 3-4 hours to actually implement the processor. 

I see what you mean about acceptsFile() now. It should be possible for me to modify the CWS acceptsFile() to look for the gcode file inside of the zip file and then the plain file to look for PNGs and explicitly reject files that contain CWS control files. Then they should be able to share the .zip extension. I'll be a way from my printer for a few weeks starting next week and should be able to make these changes then. I'll focus the next couple of days on docs that I need access to my printer to validate.

**Comment by jmkao** [comment]
Oh, and for an icon, I think `stack-overflow` would be good, or `file-archive-o` if you want to avoid the re-use of a brand icon.

**Comment by WesGilster** [comment]
Very nice looking code by the way...

**Comment by jmkao** [comment]
Ugh, sorry, the class is `fa-stack-overflow`...

**Pull request merged**
