### PR TITLE
Build structure changes to gradle convention

### PR DESCRIPTION
**Pull request by jmkao**
Moved main and test java src into src/main and src/test following the standard build convention, along with separating code from resources.

Gradle build now functions without needing any sourceSet configurations.

Also generate a jar with tests and include it with the application distribution. This was previously missing and would prevent the testkit from running (which still doesn't run because newstart.sh needs to more work, but the build now does everything it needs to).

### CODE REVIEW

**Comment by jmkao** [comment]
If you have a large number of unpushed changes, reject this and we can do it later, otherwise there could be confusing overlaps since source files are moving around.

**Comment by WesGilster** [comment]
I do have a few changes including a fix to the recent bug you opened. Could I get these changed checked in before we address this?

**Comment by WesGilster** [comment]
I checked my changes in, and I'll refrain from changing anything more to keep away from conflicts.

**Comment by jmkao** [comment]
I've merged in the changes you've checked in and the test suite runs clean. (Actually, git did most of the work, there were only a few files that moved in both repos that confused it).

**Pull request merged**
