### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by kloknibor**

### CODE REVIEW

**Comment by WesGilster** [comment]
Is there a way we can make this commit a bit more reasonable? I have no idea what I would be accepting.

**Comment by jmkao** [comment]
I think Robin synced his repo to area515 post-cleanup and this commits reflect the ones that were re-written to remove the old binaries. They should disappear once WesGilster is also synced to the post-cleanup area515 repo.

**Comment by WesGilster** [comment]
Ok. If it was just a sync after cleanup, I wasn't expecting to see conflicts so soon after my last push to area515. I'll pull this in.

**Comment by jmkao** [comment]
Not sure what the intent was, but that branch in Robin's repo doesn't seem to have the correct commit history in it. You probably shouldn't do it until the number of commits drops to a number where the changes can be identified. Anything around 520-525 commits is a hint that a repo doesn't have the cleanup applied yet.

**Comment by kloknibor** [comment]
Whoops! I only made a small change in 2 files, not even sure what it was, and did it from within the github editor. If you don't have writing acces it will make such an patch. But all these files shouldn't have been changed! I'll look into what I changed an do a new pull request! Sorry to bother you!

**Comment by jmkao** [comment]
My suggestion would be to leave the in-application link to the front page of Github, and have the PR update the README.md to point to the main website, wiki, and forum, as well as make Issues and recent changes visible. I think that will give us more flexibility.

**Pull request closed without merging**
